name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        # Publish to NPMJS
      - uses: actions/setup-node@master
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org/"
      - name: Publish to NPMJS
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm config set scope "<@OWNER>"
          npm config list
          npm publish --access public
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: |
          echo "registry=https://registry.npmjs.org/" > ~/.npmrc
          echo "@eepson123tw:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
